### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by pabloscloud** [pabloscloud/Overload#7]
**opened 7 months ago by Testgfsghvf**

**Problem:** What am I tracking? My study time, my sport time...
**Solution:** When pressing start, show popup with labels predefined by user (colour optional)

> pabloscloud commented 7 months ago (Owner)
> I already had this in mind, but I had several ideas on how to do this. I would like this to be as simple as possible.
> I would appreciate some suggestions. What would show up in the lists on the calendar tab? Would the entire app change when you select a different category, or would there be an option to filter by category on certain days?
> I'm still tinkering with how I would implement this.

> pabloscloud commented 7 months ago (edited) (Owner)
> Also wouldn't a popup be annoying. Say you do sports and press pause and start for every exercise?
> My initial idea was that one can select the current category (say in the configuration tab) and the whole app adapts.
> Current workaround (from v.0.10.0):
> backup the items of the current category
> delete storage of the app
> start creating some new items
> backup the items
> delete storage of the app
> import whatever category you want

> Testgfsghvf commented 7 months ago (Author)
> One option if you dont want to popup is, once it has started, you can press over the line of time and appears a list with categories. With this you have the convenience of pausing and resume whenever you want and label timelines

> pabloscloud commented 7 months ago (Owner)
> Another option would be to add an expandable FAB

> pabloscloud commented 7 months ago (edited) (Owner)
> I started developing it and encountered more and more areas that still need to be taken into consideration before developing it any further.
> My approach is that the user can select the current category – say work. This would start new items as work. If the user now ends working and starts tracking a new category – say school –, would this create a pause between work and school or are pauses only created between items of the same category?
> If the current category is selected does this mean only those items (and the pauses of this category, if those are by category as questioned earlier) would show or do all show up?
> Are all items shown in the calendars sheet or only the ones from the current category?

> pabloscloud commented 6 months ago (Owner)
> Current state is that I couldn't figure out a way to detect if the FAB is long pressed or just yk.. pressed

> pabloscloud commented 5 months ago (Owner)
> [https://stackoverflow.com/questions/77260254/implement-long-press-fab-in-jetpack-compose](https://stackoverflow.com/questions/77260254/implement-long-press-fab-in-jetpack-compose)

> pabloscloud commented 3 months ago (Owner)
> ![image](https://github.com/pabloscloud/Overload/assets/93644977/12d3faf2-cae5-435c-aa0a-95b5c579853c)

**Comment by pabloscloud** [comment]
### Tasks for Adding Categories and Displaying Time Spans by Categories

#### Database Changes:
- [ ] Research and understand current database structure
- [ ] Modify database schema to include categories
- [ ] Test and debug database changes

#### UI Changes:
- [ ] Research Jetpack Compose documentation for UI components
- [ ] Design new UI layout for displaying time spans with categories
- [ ] Implement UI changes in the app
- [ ] Test and refine the UI

#### Menu and FAB Updates:
- [ ] Understand current settings menu implementation
- [ ] Add new settings option for creating categories
- [ ] Add new FAB button(s)
- [ ] Test and debug menu and FAB additions

#### Adjustments to Data Structure or Retrieval Methods:
- [ ] Evaluate current data structure and retrieval methods
- [ ] Modify data structure or retrieval methods to include category information
- [ ] Test and debug data structure changes

#### Backup Implementation:
- [ ] Research backup methods and strategies
- [ ] Implement new backup version to include category names, icons, colours, etc.
     - [ ] Modify backup process to include both items table and categories
- [ ] Test backup functionality to ensure all necessary data is included

#### Overall:
- [ ] Test the entire application flow with category support
- [ ] Ensure compatibility and responsiveness across devices
- [ ] Document changes and update README if necessary
- [ ] Prepare for code review and deployment

### Estimated Time: 20-40 hours

**Comment by pabloscloud** [comment]
waiting for #28 to be completed

**Comment by pabloscloud** [comment]
04864592ff7a08c7ab759a9c76fc15608e191384
a587521ff1414504de2e9303a3f2e92cb2f1b75a
7ff19d7f22b60d2b5a3f15ed4022604af5a39791

**Comment by pabloscloud** [comment]
ad79b479454de60b5dd9f5b08078451f8e26a4d4
83a88085e2643ff1848ad0037294d2f0f8ff7778
bcb7f84f3d965167d38f71f2763d0556e036ef26
7e8d3e2c3f026661f665efbeb57363b06c1656ab

**Comment by pabloscloud** [comment]
https://github.com/pabloscloud/Overload/commit/04864592ff7a08c7ab759a9c76fc15608e191384
https://github.com/pabloscloud/Overload/commit/a587521ff1414504de2e9303a3f2e92cb2f1b75a
https://github.com/pabloscloud/Overload/commit/7ff19d7f22b60d2b5a3f15ed4022604af5a39791
https://github.com/pabloscloud/Overload/commit/ad79b479454de60b5dd9f5b08078451f8e26a4d4
https://github.com/pabloscloud/Overload/commit/83a88085e2643ff1848ad0037294d2f0f8ff7778
https://github.com/pabloscloud/Overload/commit/bcb7f84f3d965167d38f71f2763d0556e036ef26
https://github.com/pabloscloud/Overload/commit/7e8d3e2c3f026661f665efbeb57363b06c1656ab
d6c9197c5ddd90b143ac0ed8926733fc7b3a7f13
daf729b3d89fa3c006e83b0c40e66cc978969d51
